baseURL = "http://tika.asiapacificdigital.co.nz/"
languageCode = "en-us"
theme = "airspace-hugo-master"
title = "Asia Pacific Digital"
[[menu.footer]]
name = "About us test"
url = "/work"
weight = 1
[[menu.footer]]
name = "Contact us"
url = "/contact"
weight = 2
[[menu.footer]]
name = "Blog"
url = "/blog"
weight = 3
[[menu.header]]
name = "About Us"
url = "/work"
weight = 3
[[menu.header]]
name = "Blog"
url = "/blog"
weight = 4
[[menu.header]]
name = "Services"
url = "/service"
weight = 1
[[menu.header]]
name = "Contact"
url = "/contact"
weight = 5
[[menu.header]]
name = "KartikaCloudfront"
url = "/kartikanewpage"
weight = 2
[params]
dateFormat = "2 January 2006"
home = "Home"
[params.blog]
enable = true
title = "Written By Our Own People. Enjoy!"
[params.call]
enable = true
paragraph = ""
title = "Through the power of digital transformation we deliver experiences people love"
[params.call.button]
text = "Get in touch"
url = "/contact"
[params.contact]
enable = true
subtitle = "Don’t just take our word for it. Check out some of our latest work."
title = "We’d Love To Hear From You"
[params.contact.box]
address = "Level 1, 4 Newton Road, Grey Lynn, Auckland New Zealand"
email = "Email: hellonz@apdgroup.com"
phone = ""
title = "Stop by for a visit"
[params.contact.form]
button = "Send message"
email = "Your email"
message = "Your message"
name = "Your name"
subject = "Your Phone number"
[params.contact.gmaps]
title = "We Also Count in Google Maps"
[params.feature]
content = "Through the power of digital transformation and brand strategy, we redefine relationships with the digital and physical worlds to deliver experiences people love. With our strategy, technology and design experience, we make the complex simple and create new ways to engage your customers through personalised, seamless marketing journeys"
enable = true
title = "We bring digital services and experiences to life"
[params.feature.button]
caption = "View Services"
url = "/contact"
[params.service]
enable = true
title = "We Create Experiences And Grow Businesses."
[params.slider]
enable = true
subtitle = "Bringing digital services and experiences to life."
title = "Welcome To Asia Pacific Digital's"
[params.terms]
enable = true
title = "Terms"
[params.wrapper]
enable = true
italic = ""
paragraph = "Through the power of digital transformation and brand strategy, we redefine relationships with the digital and physical worlds, to deliver experiences people love. We create new ways to engage customers through personalised, seamless marketing journeys. Through strategy, technology, marketing automation and customer design experiences, we make the complex simple. From marketing communications to complex business transformations, we develop the solutions to help your business grow."
title = ""
