title = "Asia Pacific Digital"
baseURL = "http://apd-nz-promosite.s3-website-us-east-1.amazonaws.com/"
languageCode = "en-us"
theme = "airspace-hugo-master"
#relativeURLs = true

[menu]

  [[menu.header]]
    weight = 3
    name = "About Us"
    url = "/work"
  [[menu.header]]
    weight = 4
    name = "Blog"
    url = "/blog"
  [[menu.header]]
    weight = 2
    name = "Service"
    url = "/service"
  [[menu.header]]
    weight = 5
    name = "Contact"
    url = "/contact"

  [[menu.footer]]
    weight = 1
    name = "About us"
    url = "/work"
  [[menu.footer]]
    weight = 2
    name = "Contact us"
    url = "/contact"
  [[menu.footer]]
    weight = 4
    name = "Blog"
    url = "/blog"


# The site's parameters
[params]

  # If you want to remove the copyright text you need a Themefisher license.
  # This license is offered with a 50% discount for all Hugo users.
  # For information see https://github.com/gohugoio/hugoThemes/issues/260

  dateFormat = "2 January 2006"

  home = "Home"

  [params.slider]
    enable = true
    title = "Welcome To Asia Pacific Digital's"
    subtitle = "Bringing digital services and experiences to life."

  [params.terms]
    enable = true
    title = "Terms"

  [params.service]
    enable = true
    title = "We Create Experiences And Grow Businesses."

  [params.wrapper]
    enable = true
    title = ""
    italic = ""
    paragraph = "Through the power of digital transformation and brand strategy, we redefine relationships with the digital and physical worlds, to deliver experiences people love. We create new ways to engage customers through personalised, seamless marketing journeys. Through strategy, technology, marketing automation and customer design experiences, we make the complex simple. From marketing communications to complex business transformations, we develop the solutions to help your business grow."

  [params.blog]
    enable = true
    title = "Written By Our Own People. Enjoy!"

  [params.feature]
    enable = true
    title = "We bring digital services and experiences to life"
    content = "Through the power of digital transformation and brand strategy, we redefine relationships with the digital and physical worlds to deliver experiences people love. With our strategy, technology and design experience, we make the complex simple and create new ways to engage your customers through personalised, seamless marketing journeys"
    [params.feature.button]
      caption = "View Services"
      url = "/contact"

  [params.call]
    enable = true
    title = "Through the power of digital transformation we deliver experiences people love"
    paragraph = ""
    [params.call.button]
      text = "Get in touch"
      url = "/contact"

  [params.contact]
    enable = true
    title = "We’d Love To Hear From You"
    subtitle = "Don’t just take our word for it. Check out some of our latest work."
    [params.contact.form]
      name = "Your name"
      email = "Your email"
      subject = "Your Phone number"
      message = "Your message"
      button = "Send message"
    [params.contact.box]
      title = "Stop by for a visit"
      address = "Level 1, 4 Newton Road, Grey Lynn, Auckland New Zealand"
      email = "Email: hellonz@apdgroup.com"
      phone = ""
    [params.contact.gmaps]
      title = "We Also Count in Google Maps"
